CREATE TABLE users (
       id BIGINT AUTO_INCREMENT PRIMARY KEY,
       name VARCHAR(255) NOT NULL UNIQUE,
       password_hash VARCHAR(255) NOT NULL,
       pin_hash VARCHAR(255),
       role VARCHAR(20) NOT NULL,
       active BOOLEAN NOT NULL DEFAULT TRUE
)